### PR TITLE
Add color back in to output after processing completed; minor output formatting

### PR DESCRIPTION
**Pull request by localpcguy**
I liked this, but missed the color output. This change adds it back in (after all processing is done) for the different severity levels and a couple other spots in the output to more closely mimic the original output.

### CODE REVIEW

**Comment by adrianosela** [comment]
Hi @localpcguy thanks for this. I havent touched Snyk in a while. 

Would you be able to post some test output / screenshots? And ideally some info on the snyk cli version tested with and as much detail as you can?

**Comment by adrianosela** [comment]
Last change i made (years ago) i claimed it worked for version 1.1019.0 — would you mind testing with that version as well?

**Comment by localpcguy** [comment]
I added the version I was using to the README, but I'd prefer not to downgrade to test older versions. I did not have to change any of the parsing logic though for the version I was on, so I expect it should work. 

NOTE: I did block out file paths and organization id in the screenshots

Original (no color)
snyk_code_ignore-no_color

Updated (added color back after processing)
snyk_code_ignore-added_color

**Comment by adrianosela** [comment]
Lgtm @localpcguy - thanks!

**Pull request merged**
